const cfg=window.RINDIK_SUPABASE;const db=window.supabase.createClient(cfg.url,cfg.publishableKey);let mode='login',activeForm='',orders=[],attendance=[],targets=[];
const el=id=>document.getElementById(id);const money=v=>'Rp '+new Intl.NumberFormat('id-ID',{maximumFractionDigits:0}).format(Number(v||0));const date=v=>new Date(v+'T00:00:00').toLocaleDateString('id-ID',{day:'2-digit',month:'short',year:'numeric'});
function setView(view){document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));el(view).classList.add('active');document.querySelectorAll('[data-view]').forEach(x=>x.classList.toggle('active',x.dataset.view===view));location.hash=view;document.querySelector('aside').classList.remove('open')}
document.querySelectorAll('[data-view]').forEach(a=>a.onclick=e=>{e.preventDefault();setView(a.dataset.view)});el('menu').onclick=()=>document.querySelector('aside').classList.toggle('open');
function render(){el('salesTotal').textContent=money(orders.reduce((n,o)=>n+Number(o.total_amount),0));el('ordersTotal').textContent=orders.length;el('attendanceTotal').textContent=attendance.filter(a=>a.attendance_date===new Date().toISOString().slice(0,10)&&a.status==='Hadir').length;el('targetsTotal').textContent=targets.length;const cells=o=>`<tr><td>${o.customer_name}</td><td>${o.product_name}</td><td>${money(o.total_amount)}</td><td><span class="tag">${o.status}</span></td></tr>`;el('recentOrders').innerHTML=orders.slice(0,5).map(cells).join('')||'<tr><td colspan="4">Belum ada pesanan.</td></tr>';el('ordersRows').innerHTML=orders.map(o=>`<tr><td>${date(o.order_date)}</td>${cells(o).replace('<tr>','').replace('</tr>','')}</tr>`).join('')||'<tr><td colspan="5">Belum ada pesanan.</td></tr>';el('attendanceRows').innerHTML=attendance.map(a=>`<tr><td>${a.employee_name}</td><td>${a.division||'—'}</td><td>${date(a.attendance_date)}</td><td>${a.check_in?new Date(a.check_in).toLocaleTimeString('id-ID',{hour:'2-digit',minute:'2-digit'}):'—'}</td><td><span class="tag">${a.status}</span></td></tr>`).join('')||'<tr><td colspan="5">Belum ada absensi.</td></tr>';el('targetsRows').innerHTML=targets.map(t=>{const pct=Math.min(100,Math.round(Number(t.current_value)/Number(t.target_value)*100));return `<article class="panel target"><h3>${t.title}</h3><p>${money(t.current_value)} dari ${money(t.target_value)} · ${t.period_label}</p><div class="bar"><i style="width:${pct}%"></i></div><p><b>${pct}% tercapai</b></p></article>`}).join('')||'<section class="panel"><p>Belum ada target. Tambahkan target pertama Anda.</p></section>'}
async function load(){const [o,a,t,s]=await Promise.all([db.from('orders').select('*').order('created_at',{ascending:false}),db.from('attendance').select('*').order('attendance_date',{ascending:false}),db.from('business_targets').select('*').order('created_at',{ascending:false}),db.from('app_settings').select('*').eq('id','company').maybeSingle()]);if(o.error||a.error||t.error||s.error){alert('Gagal memuat data. Periksa koneksi Supabase.');return}orders=o.data;attendance=a.data;targets=t.data;if(s.data){el('companyName').value=s.data.company_name;el('adminName').value=s.data.admin_name;el('headerName').textContent=s.data.company_name}render()}
function openForm(type){activeForm=type;el('modal').hidden=false;el('formMessage').textContent='';const maps={order:['INPUT PESANAN','Tambah Pesanan',`<label>Nama pelanggan<input name="customer_name" required></label><label>Produk<input name="product_name" required></label><label>Nilai penjualan<input name="total_amount" type="number" min="0" required></label><label>Status<select name="status"><option>Baru</option><option>Menunggu Pembayaran</option><option>Diproduksi</option><option>Siap Kirim</option><option>Selesai</option></select></label>`],attendance:['ABSENSI KARYAWAN','Catat Kehadiran',`<label>Nama karyawan<input name="employee_name" required></label><label>Divisi<input name="division"></label><label>Status<select name="status"><option>Hadir</option><option>Terlambat</option><option>Izin</option><option>Sakit</option></select></label>`],target:['TARGET BISNIS','Tambah Target',`<label>Nama target<input name="title" required></label><label>Nilai target<input name="target_value" type="number" min="1" required></label><label>Realisasi saat ini<input name="current_value" type="number" min="0" value="0" required></label><label>Periode<input name="period_label" value="Bulanan" required></label>`]};const m=maps[type];el('formEyebrow').textContent=m[0];el('formTitle').textContent=m[1];el('formFields').innerHTML=m[2]}
document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>openForm(b.dataset.open));el('closeModal').onclick=()=>el('modal').hidden=true;
el('dataForm').onsubmit=async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target));let table=activeForm;if(table==='target')table='business_targets';if(activeForm==='attendance'){data.attendance_date=new Date().toISOString().slice(0,10);if(data.status==='Hadir'||data.status==='Terlambat')data.check_in=new Date().toISOString()}if(activeForm==='order')data.order_date=new Date().toISOString().slice(0,10);const {error}=await db.from(table).insert(data);if(error){el('formMessage').textContent=error.message;return}el('modal').hidden=true;e.target.reset();await load()};
el('settingsForm').onsubmit=async e=>{e.preventDefault();const {error}=await db.from('app_settings').upsert({id:'company',company_name:el('companyName').value.trim(),admin_name:el('adminName').value.trim(),updated_at:new Date().toISOString()});el('settingsMessage').textContent=error?error.message:'✓ Pengaturan tersimpan.';if(!error)await load()};
el('authSwitch').onclick=()=>{mode=mode==='login'?'signup':'login';el('authButton').textContent=mode==='login'?'Masuk':'Daftar';el('authSwitch').textContent=mode==='login'?'Belum punya akun? Daftar':'Sudah punya akun? Masuk';el('authMessage').textContent=''};
el('authForm').onsubmit=async e=>{e.preventDefault();el('authMessage').textContent='Memproses...';const email=el('email').value,password=el('password').value;const result=mode==='login'?await db.auth.signInWithPassword({email,password}):await db.auth.signUp({email,password});if(result.error){el('authMessage').textContent=result.error.message;return}el('authMessage').textContent=mode==='signup'?'Periksa email untuk konfirmasi akun, lalu masuk.':'Berhasil masuk.'};
async function start(){const {data:{session}}=await db.auth.getSession();if(!session)return;el('authScreen').hidden=true;el('app').hidden=false;el('userEmail').textContent=session.user.email;await load();const requested=location.hash.slice(1);if(requested&&el(requested))setView(requested)}db.auth.onAuthStateChange((_event,session)=>{if(session)start()});el('logout').onclick=()=>db.auth.signOut().then(()=>location.reload());start();
