let orders = [
  ['#RA-2052','Ni Luh Putu','Rindik Ukir Klasik','27 Agu 2026','Rp 4.850.000','Baru','NP','#c88477'],
  ['#RA-2051','Sari Wulandari','Rindik Bali Premium','26 Agu 2026','Rp 3.250.000','Menunggu Pembayaran','SW','#9585a9'],
  ['#RA-2050','Komang Art Shop','Rindik Mini Souvenir (10 pcs)','26 Agu 2026','Rp 6.500.000','Diproduksi','KA','#c79b62'],
  ['#RA-2049','Michael Anderson','Rindik Ukir Klasik','25 Agu 2026','Rp 5.750.000','Siap Kirim','MA','#7899a4'],
  ['#RA-2048','Dewa Made','Rindik Bali Premium','24 Agu 2026','Rp 4.100.000','Diproduksi','DM','#79926e']
];
try{const savedOrders=JSON.parse(localStorage.getItem('rindik-orders'));if(Array.isArray(savedOrders)&&savedOrders.length)orders=savedOrders}catch(e){}
const saveOrders=()=>localStorage.setItem('rindik-orders',JSON.stringify(orders));
const statusClass = s => s === 'Baru' ? 'yellow' : s === 'Menunggu Pembayaran' ? 'red' : s === 'Diproduksi' ? 'green-tag' : 'green-tag';
function rows(list){return list.map(o=>`<tr><td>${o[0]}</td><td><div class="customer"><span class="avatar" style="background:${o[7]}">${o[6]}</span>${o[1]}</div></td><td>${o[2]}</td><td>${o[3]}</td><td><b>${o[4]}</b></td><td><span class="tag ${statusClass(o[5])}">${o[5]}</span></td><td class="dots">•••</td></tr>`).join('')}
function renderOrders(){document.querySelector('#orderRows').innerHTML=rows(orders.slice(0,4));document.querySelector('#allOrderRows').innerHTML=rows(orders);saveOrders()}
renderOrders();
document.querySelectorAll('[data-view]').forEach(link=>link.addEventListener('click',e=>{e.preventDefault();document.querySelectorAll('[data-view]').forEach(x=>x.classList.remove('active'));document.querySelectorAll(`[data-view="${link.dataset.view}"]`).forEach(x=>x.classList.add('active'));document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));document.querySelector('#'+link.dataset.view).classList.add('active');document.querySelector('.sidebar').classList.remove('open')}));
document.querySelectorAll('[data-target]').forEach(btn=>btn.addEventListener('click',()=>document.querySelector(`[data-view="${btn.dataset.target}"]`).click()));
const modal=document.querySelector('#modal');const openModal=()=>{modal.classList.add('open');document.querySelector('#customerInput').focus()};document.querySelector('#newOrder').onclick=openModal;document.querySelector('#newOrder2').onclick=openModal;['#closeModal','#cancelModal'].forEach(s=>document.querySelector(s).onclick=()=>modal.classList.remove('open'));modal.addEventListener('click',e=>{if(e.target===modal)modal.classList.remove('open')});
document.querySelector('.modal').addEventListener('submit',e=>{e.preventDefault();const customer=document.querySelector('#customerInput').value.trim();const product=document.querySelector('#productInput').value;const rawTotal=document.querySelector('#totalInput').value.replace(/[^0-9]/g,'');if(!customer||!rawTotal)return;const initials=customer.split(' ').map(x=>x[0]).slice(0,2).join('').toUpperCase();const total=new Intl.NumberFormat('id-ID').format(Number(rawTotal));const today=new Date().toLocaleDateString('id-ID',{day:'2-digit',month:'short',year:'numeric'});orders.unshift(['#RA-'+(2053+orders.length),customer,product,today,'Rp '+total,'Baru',initials,'#789e8d']);renderOrders();modal.classList.remove('open');document.querySelector('#customerInput').value='';document.querySelector('#totalInput').value='';document.querySelector('[data-view="orders"]').click()});
document.querySelector('.menu-btn').onclick=()=>document.querySelector('.sidebar').classList.toggle('open');
document.querySelector('.search').addEventListener('input',e=>{const q=e.target.value.toLowerCase();document.querySelector('#allOrderRows').innerHTML=rows(orders.filter(o=>o.join(' ').toLowerCase().includes(q)))});
const board=[['Perlu Dijadwalkan',['#RA-2052 · Ni Luh Putu','Rindik Ukir Klasik']],['Sedang Dikerjakan',['#RA-2048 · Dewa Made','Rindik Bali Premium'],['#RA-2050 · Komang Art Shop','10 Rindik Mini Souvenir']],['Siap Quality Check',['#RA-2049 · Michael Anderson','Rindik Ukir Klasik']]];document.querySelector('#kanban').innerHTML=board.map(c=>`<div class="kanban-column"><h3>${c[0]}</h3>${c.slice(1).map(j=>`<div class="job"><b>${j[0]}</b><p>${j[1]}</p></div>`).join('')}</div>`).join('');
const products=[['Rindik Ukir Klasik','Bambu pilihan dengan ukiran tradisional','Rp 4.850.000','R'],['Rindik Bali Premium','Nada jernih, finishing kayu eksklusif','Rp 4.100.000','R'],['Rindik Mini Souvenir','Cinderamata khas Bali yang elegan','Rp 650.000','r']];document.querySelector('#productGrid').innerHTML=products.map(p=>`<article class="product"><div class="product-art">${p[3]}</div><h3>${p[0]}</h3><p>${p[1]}</p><b>${p[2]}</b></article>`).join('');
const attendance=[['I Made Sutama','Pengrajin','07.42','—','Berjalan','Hadir','MS','#77936d'],['Kadek Ayu Lestari','Finishing','07.55','—','Berjalan','Hadir','KL','#bd866f'],['Wayan Putra','Pengrajin','08.17','—','Berjalan','Terlambat','WP','#8c93b0'],['Ni Komang Sri','Administrasi','07.48','—','Berjalan','Hadir','NS','#ba9b61'],['Gede Arta','Pengemasan','07.51','—','Berjalan','Hadir','GA','#779e96'],['Putu Dewi','Pemasaran','—','—','—','Izin','PD','#a3899f']];
const attendanceClass=s=>s==='Hadir'?'green-tag':s==='Terlambat'?'yellow':'red';
function renderAttendance(){document.querySelector('#attendanceRows').innerHTML=attendance.map(a=>`<tr><td><div class="customer"><span class="avatar" style="background:${a[7]}">${a[6]}</span>${a[0]}</div></td><td>${a[1]}</td><td>${a[2]}</td><td>${a[3]}</td><td>${a[4]}</td><td><span class="tag ${attendanceClass(a[5])}">${a[5]}</span></td><td class="dots">•••</td></tr>`).join('')}renderAttendance();
document.querySelector('#checkInBtn').addEventListener('click',function(){const now=new Date().toLocaleTimeString('id-ID',{hour:'2-digit',minute:'2-digit'});attendance.unshift(['Aditya Dharma','Administrator',now,'—','Berjalan','Hadir','AD','#d8a574']);renderAttendance();document.querySelector('#presentCount').textContent='15';this.textContent='✓ Sudah Check-in';this.disabled=true});
document.querySelector('#downloadAttendance').addEventListener('click',()=>{const header='Karyawan,Divisi,Check-in,Check-out,Durasi,Status';const data=attendance.map(a=>a.slice(0,6).join(','));const blob=new Blob([[header,...data].join('\n')],{type:'text/csv'});const link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download='rekap-absensi-rindik-art.csv';link.click();URL.revokeObjectURL(link.href)});
const targets=[['Penjualan Bulanan','Rp 48.750.000','Rp 65.000.000',75,'green'],['Pesanan Selesai','32 pesanan','40 pesanan',80,'green'],['Produksi Tepat Waktu','18 pesanan','25 pesanan',72,'warn'],['Pelanggan Baru','12 pelanggan','10 pelanggan',120,'violet']];
function renderTargets(){document.querySelector('#targetGrid').innerHTML=targets.map(t=>`<article class="panel target-card"><div class="target-card-top"><div><h3>${t[0]}</h3><p>Target Agustus 2026</p></div><span class="tag ${t[3]>=100?'green-tag':'yellow'}">${t[3]>=100?'Tercapai':'Berjalan'}</span></div><div class="target-value">${t[1]} <span>/ ${t[2]}</span></div><div class="progress-track"><div class="progress-fill ${t[4]}" style="width:${Math.min(t[3],100)}%"></div></div><div class="target-footer"><span>Progres saat ini</span><b>${t[3]}%</b></div></article>`).join('')}renderTargets();
document.querySelector('#addTarget').addEventListener('click',function(){targets.push(['Kunjungan Workshop','18 kunjungan','30 kunjungan',60,'blue']);renderTargets();this.textContent='✓ Target Ditambahkan';this.disabled=true});
let installPrompt;const installButton=document.querySelector('#installApp');window.addEventListener('beforeinstallprompt',event=>{event.preventDefault();installPrompt=event;installButton.hidden=false});installButton.addEventListener('click',async()=>{if(!installPrompt)return;installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;installButton.hidden=true});
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js').catch(()=>{}));
const getInitials=name=>name.split(' ').filter(Boolean).map(part=>part[0]).slice(0,2).join('').toUpperCase()||'AD';
function renderProfile(){const name=localStorage.getItem('rindik-admin-name')||'Aditya Dharma';const initials=getInitials(name);document.querySelector('#profileName').textContent=name;document.querySelector('#profileInitials').textContent=initials;document.querySelector('#settingsInitials').textContent=initials;document.querySelector('#greetingName').textContent=name.split(' ')[0];document.querySelector('#adminNameInput').value=name}renderProfile();
document.querySelector('#profileForm').addEventListener('submit',event=>{event.preventDefault();const name=document.querySelector('#adminNameInput').value.trim();if(!name)return;localStorage.setItem('rindik-admin-name',name);renderProfile();document.querySelector('#profileSaved').textContent='✓ Nama administrator berhasil disimpan.'});
