(()=>{
const cfg=window.RINDIK_SUPABASE;if(!cfg)return;
const dbx=window.supabase.createClient(cfg.url,cfg.publishableKey);
let qrPromise=null,scan=null,scanRunning=false;
const $=id=>document.getElementById(id),todayX=()=>new Date().toLocaleDateString('en-CA');
const escX=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function loadScript(src){return new Promise((res,rej)=>{const s=document.createElement('script');s.src=src;s.onload=res;s.onerror=rej;document.head.appendChild(s)})}
async function qrLib(){if(window.QRCode)return window.QRCode;if(!qrPromise)qrPromise=loadScript('https://cdn.jsdelivr.net/npm/qrcodejs@1.0.0/qrcode.min.js');await qrPromise;return window.QRCode}
async function scannerLib(){if(window.Html5Qrcode)return window.Html5Qrcode;await loadScript('https://unpkg.com/html5-qrcode@2.3.8/html5-qrcode.min.js');return window.Html5Qrcode}
function ensureScanButton(){const h=document.querySelector('#attendance .heading-actions');if(h&&!$('scanAttendanceBtn'))h.insertAdjacentHTML('afterbegin','<button class="secondary" id="scanAttendanceBtn" type="button">📷 Scan QR</button>')}
async function employeeRows(){const rows=document.querySelectorAll('#employeesRows tr');for(const row of rows){if(row.querySelector('[data-employee-qr]'))continue;const edit=row.querySelector('[data-action="edit"][data-table="employees"]');if(!edit)continue;const id=edit.dataset.id;const cell=row.querySelector('.actions');if(cell)cell.insertAdjacentHTML('afterbegin','<button type="button" class="row-btn" data-employee-qr="'+escX(id)+'">QR</button>')}}
async function showEmployeeQR(id){const {data:e,error}=await dbx.from('employees').select('*').eq('id',id).maybeSingle();if(error||!e){alert('Data karyawan tidak ditemukan.');return}const modal=$('qrModal'),box=$('qrCode');if(!modal||!box)return;box.innerHTML='';$('qrTitle').textContent='QR Absensi — '+(e.name||'Karyawan');$('qrSub').textContent=(e.employee_code||'')+' · Scan untuk check-in / check-out';try{await qrLib();new QRCode(box,{text:'RINDIK-EMP-ABSEN|'+e.id+'|'+encodeURIComponent(e.employee_code||'')+'|'+encodeURIComponent(e.name||''),width:220,height:220,colorDark:'#20362d',colorLight:'#ffffff',correctLevel:QRCode.CorrectLevel.M});modal.hidden=false}catch(err){alert('QR belum dapat dimuat. Periksa koneksi internet.')}}
async function stop(){if(scan&&scanRunning){try{await scan.stop();await scan.clear()}catch(e){}}scan=null;scanRunning=false}
async function processQR(text){const p=String(text||'').split('|');if(p[0]!=='RINDIK-EMP-ABSEN'||!p[1])return setMsg('QR tidak dikenali. Gunakan QR dari menu Karyawan Toko.');const {data:e,error}=await dbx.from('employees').select('*').eq('id',p[1]).maybeSingle();if(error||!e)return setMsg('Data karyawan tidak ditemukan.');setMsg('Memproses '+e.name+'...');const d=todayX();const q=await dbx.from('attendance').select('*').eq('attendance_date',d).eq('employee_id',e.id).order('created_at',{ascending:false}).limit(1);if(q.error)return setMsg('Gagal membaca absensi: '+q.error.message);const open=q.data?.find(x=>!x.check_out);if(open){const u=await dbx.from('attendance').update({check_out:new Date().toISOString()}).eq('id',open.id);if(u.error)setMsg('Gagal check-out: '+u.error.message);else{setMsg('✓ '+e.name+' berhasil check-out.');setTimeout(()=>location.reload(),900)}}else{const u=await dbx.from('attendance').insert({employee_id:e.id,employee_name:e.name,division:e.division||e.position||'',attendance_date:d,check_in:new Date().toISOString(),status:'Hadir',notes:'Absensi QR'});if(u.error)setMsg('Gagal check-in: '+u.error.message);else{setMsg('✓ '+e.name+' berhasil check-in.');setTimeout(()=>location.reload(),900)}}}
function setMsg(v){const x=$('scanMessage');if(x)x.textContent=v}
async function start(){try{await scannerLib();await stop();scan=new Html5Qrcode('qr-reader');scanRunning=true;await scan.start({facingMode:'environment'},{fps:10,qrbox:{width:250,height:250}},processQR,()=>{})}catch(e){scanRunning=false;setMsg('Kamera tidak dapat dibuka. Izinkan akses kamera di browser/HP lalu coba lagi.')}}
function ensureObserver(){const target=$('employeesRows');if(!target)return;new MutationObserver(()=>employeeRows()).observe(target,{childList:true,subtree:true});employeeRows()}
document.addEventListener('click',async e=>{const q=e.target.closest('[data-employee-qr]');if(q){e.preventDefault();e.stopPropagation();await showEmployeeQR(q.dataset.employeeQr);return}if(e.target.closest('#scanAttendanceBtn')){e.preventDefault();const m=$('scannerModal');if(m){m.hidden=false;setMsg('Arahkan kamera ke QR karyawan.');setTimeout(start,120)}return}if(e.target.closest('#closeScanner,#stopScanner')){await stop();const m=$('scannerModal');if(m)m.hidden=true}} ,true);
window.addEventListener('load',()=>{ensureScanButton();ensureObserver()});
})();